name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup target add wasm32-unknown-unknown
      - name: Build Lingua Registry
        run: |
          cd contracts/lingua-registry
          cargo build --target wasm32-unknown-unknown --release
          # Dosyayı bulup kopyalamak için mutlak yolu kullanıyoruz
          cp $(find target -name "*.wasm") ../../lingua_registry.wasm
      - name: Run Contract Tests
        run: cd contracts && cargo test

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: cd linguachain-frontend && npm install
      - name: Build Frontend
        run: cd linguachain-frontend && npm run build